---
# - name: Update all packages to latest
#   ansible.builtin.dnf:
#     name: "*"
#     state: latest
- name: Add EPEL repo
  ansible.builtin.dnf:
    name:
      - epel-release
- name: Add OpenNebula repo
  ansible.builtin.yum_repository:
    name: opennebula
    description: OpenNebula Community Edition
    baseurl: https://downloads.opennebula.io/repo/6.8/AlmaLinux/$releasever/$basearch
    enabled: true
    gpgkey: https://downloads.opennebula.io/repo/repo2.key
    gpgcheck: true
    repo_gpgcheck: true
- name: Install pip
  ansible.builtin.dnf:
    name:
      - pip
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled