---
- name: Add Ceph key to authorized_keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'ceph.pub') }}"
- name: Install Podman
  ansible.builtin.dnf:
    name:
      - podman-4.6.1
- name: Start podman
  ansible.builtin.service:
    name: podman
    state: started
    enabled: true