---
- name: Copy SSH private key
  ansible.builtin.copy:
    src: id_rsa
    dest: /var/lib/one/.ssh/id_rsa
    owner: oneadmin
    group: oneadmin
    mode: "0600"
- name: Copy SSH public key
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: /var/lib/one/.ssh/id_rsa.pub
    owner: oneadmin
    group: oneadmin
    mode: "0600"
- name: Copy authorized_keys file
  ansible.builtin.copy:
    src: authorized_keys
    dest: /var/lib/one/.ssh/authorized_keys
    owner: oneadmin
    group: oneadmin
    mode: "0600"