- name: Apply common Ceph configuration 
  ansible.builtin.include_role:
    name: common/ceph
- name: Install pip
  ansible.builtin.dnf:
    name:
      - python3-pip-21.2.3
- name: Install init_osd.py dependencies
  ansible.builtin.pip:
    name:
      - requests==2.31.0
      - pyyaml==5.4.1
- name: Copy init_osd.py configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: ~/config.yml
    owner: root
    group: root
    mode: "0600"
- name: Initialize osd
  ansible.builtin.script: init_osd.py 
  args:
    executable: python3