---
- name: Configure and deploy controllers
  hosts: controllers
  remote_user: root
  roles:
    - frontend
- name: Configure and deploy computes
  hosts: computes
  remote_user: root
  roles:
    - node
# - name: Configure and deploy monitors
#   hosts: monitors
#   remote_user: root
#   roles:
#     - monitor
# - name: Configure and deploy osds
#   hosts: osds
#   remote_user: root
#   roles:
#     - osd
