---
- name: Update system and set-up repos
  ansible.builtin.include_role:
    name: common
- name: Install OpenNebula kvm package
  ansible.builtin.dnf:
    name:
      - opennebula-node-kvm
- name: Restart libvirtd service
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: true
- name: Join cluster
  become: true
  become_user: oneadmin
  ansible.builtin.shell: ssh oneadmin@{{ endpoint }} "onehost create $HOSTNAME -i kvm -v kvm"
