---
- name: Update system and set-up repos
  ansible.builtin.include_role:
    name: common/one
- name: Install Ceph repository
  ansible.builtin.dnf:
    name:
      - centos-release-ceph-quincy-1.0
- name: Install Ceph client
  ansible.builtin.dnf:
    name:
      - ceph-common-17.2.7
- name: Install OpenNebula kvm node package
  ansible.builtin.dnf:
    name:
      - opennebula-node-kvm-6.8.0
- name: Install init_compute.py dependencies
  ansible.builtin.pip:
    name:
      - pyone==6.8.3
      - pyyaml==5.4.1
- name: Configure SSH
  ansible.builtin.include_role:
    name: ssh
- name: Restart libvirt service
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: true
  ignore_errors: true
- name: Copy libvirt keyring
  ansible.builtin.copy:
    src: ceph.client.libvirt.keyring
    dest: /etc/ceph/ceph.client.libvirt.keyring
    owner: oneadmin
    group: oneadmin
    mode: "0600"
- name: Copy Ceph client configuration file
  ansible.builtin.template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: "0644"
- name: Copy libvirt secret configuration file
  ansible.builtin.template:
    src: secret.xml.j2
    dest: /var/lib/one/secret.xml
    owner: oneadmin
    group: oneadmin
    mode: "0644"
- name: Define libvirt secret
  become: true
  become_user: oneadmin
  ansible.builtin.shell: virsh -c qemu:///system secret-define /var/lib/one/secret.xml
- name: Set libvirt secret value
  become: true
  become_user: oneadmin
  ansible.builtin.shell: virsh -c qemu:///system secret-set-value --secret {{ secret_uuid }} --base64 {{ secret_value }}
- name: Copy init_compute.py configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: ~/config.yml
    owner: root
    group: root
    mode: "0600"
- name: Join cluster and datastores
  ansible.builtin.script: init_compute.py 
  args:
    executable: python3