---
- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - common
- name: Configure and deploy kvm nodes
  hosts: nodes
  become: true
  roles: 
    - kvm_node
- name: Configure and deploy front-end
  hosts: controllers
  become: true
  roles:
    - front_end